import PIXI from 'pixi.js';
import { BoxModel, ComputedLayout, MeasuredSize } from './box-model';
import { LayoutEngine } from '../services';
import { ThemeResolver } from '../theming/theme-resolver';
export declare abstract class UIComponent {
    container: PIXI.Container;
    protected boxModel: BoxModel;
    protected focusRing?: PIXI.Graphics;
    protected computedLayout: ComputedLayout;
    parent?: UIComponent;
    visible: boolean;
    enabled: boolean;
    protected layoutDirty: boolean;
    protected layoutEngine: LayoutEngine;
    tabIndex: number;
    protected focused: boolean;
    protected hovered: boolean;
    protected pressed: boolean;
    protected themeResolver?: ThemeResolver;
    private defaultThemeResolver?;
    constructor(boxModel?: Partial<BoxModel>);
    private createFocusRing;
    protected updateFocusRing(): void;
    abstract measure(): MeasuredSize;
    layout(availableWidth: number, availableHeight: number): void;
    protected abstract render(): void;
    markLayoutDirty(): void;
    getLayout(): ComputedLayout;
    getBoxModel(): BoxModel;
    getGlobalBounds(): {
        x: number;
        y: number;
        width: number;
        height: number;
    };
    setPosition(x: number, y: number): void;
    show(): void;
    hide(): void;
    canFocus(): boolean;
    isFocused(): boolean;
    onFocus(): void;
    protected showFocusRing(): void;
    private scrollIntoView;
    onBlur(): void;
    protected hideFocusRing(): void;
    protected getThemeResolver(): ThemeResolver;
    protected resolveColor(type: 'background' | 'border' | 'text' | 'selected' | 'hover' | 'focus' | 'disabled', override?: number): number;
    protected resolveControlColor(controlType: 'checkbox' | 'textInput' | 'textArea' | 'button' | 'radio' | 'select', type: 'background' | 'border' | 'text', override?: number): number;
    protected resolveTextColor(override?: number): number;
    protected resolvePlaceholderColor(override?: number): number;
    protected resolveCheckmarkColor(override?: number): number;
    protected makeInteractive(cursor?: string): void;
    destroy(): void;
}
